### PR TITLE
Add missing param to stbi_load_*_from_memory bindings

### PR DESCRIPTION
**Pull request by dmitrig**
This was causing `Stb.read_from_*_memory` to always fail with "unable to decode image."

### CODE REVIEW

**Comment by dmmulroy** [comment]
Would love to see this accepted and merged.

**Comment by zshipko** [comment]
Thanks, this looks good! It seems like `In_channel` which was added to a test isnt available on some of the supported versions but otherwise seems ready to merge.

**Comment by dmitrig** [comment]
Woops, forgot `In_channel` is new. Built with 4.08 this time

**Comment by zshipko** [comment]
Thanks!

**Pull request merged**
